#!/bin/sh

if [ -x /var/cfengine/bin/cf-key ]; then
        /var/cfengine/bin/cf-key
fi

start=/etc/init.d/cfengine3

if [ -f /etc/init.d/cfengine3 ];then
        for l in /etc/rc3.d/S97cfengine3 /etc/rc0.d/K05cfengine3 /etc/rc1.d/K05cfengine3 \
                /etc/rc2.d/K05cfengine3 /etc/rcS.d/K05cfengine3; do
                if [ ! -h $l ]; then
                        /usr/bin/ln -s $start $l
                fi
        done
fi

exit 0
