#!/bin/sh

case $1 in 
        'start')
                r=0
                if [ -x /usr/bin/zonename ];then
                        /usr/bin/pgrep -z `/usr/bin/zonename` cf-execd > /dev/null
                        r=$?
                else
                        /usr/bin/pgrep cf-execd > /dev/null
                        r=$?
                fi

                if [ $r -gt 0 ];then
                        /var/rudder/cfengine-community/bin/cf-execd
                else
                        echo "cf-execd seems to be running already..."
                fi
                ;;
        'stop')
                if [ -x /usr/bin/zonename ]; then
                        for b in cf-execd cf-monitord cf-serverd cf-agent cf-twin; do
                                /usr/bin/pkill -TERM -z `/usr/bin/zonename` $b
                        done
                else
                        for b in cf-execd cf-monitord cf-serverd cf-agent cf-twin; do
                                /usr/bin/pkill -TERM $b
                        done
                fi
                ;;
        *)
                echo "Usage: $0 { start | stop }"
                exit 1
                ;;
esac    
