#!/bin/sh

if [ -x /usr/bin/zonename ]; then
        for b in cf-execd cf-monitord cf-serverd cf-agent cf-hub; do
                /usr/bin/pkill -TERM -z `/usr/bin/zonename` $b
        done
else
        for b in cf-execd cf-monitord cf-serverd cf-agent cf-hub; do
                /usr/bin/pkill -TERM $b
        done
fi

/usr/bin/rm -f /etc/rc3.d/S97rudder-agent /etc/rc0.d/K05rudder-agent /etc/rc1.d/K05rudder-agent \
        /etc/rc2.d/K05rudder-agent /etc/rcS.d/K05rudder-agent 

exit 0
