#!/bin/sh
#
# This script runs FusionInventory, using either a Rudder provided instance
# or a system provided one if the first one is not usable.
#
# It also sources from /etc/profile beforehand, too fetch environment
# variables to be inserted into the inventory.
#
# Exit codes:
## 1 - Unable to find FusionInventory
## 2 - The system FusionInventory instance is too old
## 3 to inf - FusionInventory return codes

. /etc/profile

# Main

if [ -x /opt/rudder/bin/perl ]; then

  # Rudder's perl installation is present, use it.
  echo "[info] FusionInventory instance: builtin"

  /opt/rudder/bin/perl -I /opt/rudder/lib/perl5 /opt/rudder/bin/fusioninventory-agent --config=none "$@"

else

  # No usable FusionInventory installation has been detected, bail out.
  echo "[ERROR] No usable FusionInventory instance detected."
  exit 1

fi
