#####################################################################################
# Copyright 2011 Normation SAS
#####################################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, Version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#####################################################################################

.DEFAULT_GOAL := localdepends

CFENGINE_RELEASE = 3.7.0
PCRE_RELEASE = 8.37
OPENSSL_RELEASE = 0.9.8zg
ZLIB_RELEASE = 1.2.8
BZIP2_RELEASE = 1.0.6
LIBXML2_RELEASE = 2.9.2
LIBICONV_RELEASE = 1.14
OPENLDAP_RELEASE = 2.4.40
YAML_RELEASE = 0.1.5
LIBUUID_RELEASE = 1.0.3
EXPAT_RELEASE = 2.1.0
APR_RELEASE = 1.5.2
NXLOG_RELEASE = 2.8.1248
BUILD_DIR = ../build
TMP_DIR := $(shell mktemp -dq /tmp/rudder.XXXXXX)
WGET := $(if $(PROXY), http_proxy=$(PROXY) ftp_proxy=$(PROXY)) /usr/sfw/bin/wget -q
PATCH = /usr/bin/gpatch
FIND = /opt/csw/bin/gfind
TAR = /opt/csw/bin/gtar

localdepends: $(BUILD_DIR) $(BUILD_DIR)/zlib-source $(BUILD_DIR)/bzip2-source $(BUILD_DIR)/openldap-source $(BUILD_DIR)/pcre-source $(BUILD_DIR)/openssl-source $(BUILD_DIR)/cfengine-source $(BUILD_DIR)/libxml2-source $(BUILD_DIR)/libiconv-source $(BUILD_DIR)/libuuid-source $(BUILD_DIR)/expat-source $(BUILD_DIR)/apr-source $(BUILD_DIR)/nxlog-source $(BUILD_DIR)/yaml-source
	rm -rf $(TMP_DIR)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(BUILD_DIR)/cfengine-source:
	# Original URL: http://cfengine.com/source-code/download?file=cfengine-$(CFENGINE_RELEASE).tar.gz
	#$(WGET) -O $(TMP_DIR)/cfengine.tgz http://www.normation.com/tarball/cfengine-$(CFENGINE_RELEASE).tar.gz
	#$(WGET) -O $(TMP_DIR)/cfengine.tgz http://s3.amazonaws.com/cfengine.package-repos/tarballs/cfengine-$(CFENGINE_RELEASE).tar.gz
	#$(WGET) -O $(TMP_DIR)/cfengine.tgz http://cfengineers.net/files/src/cfengine-$(CFENGINE_RELEASE).tar.gz
	$(WGET) -O $(TMP_DIR)/cfengine.tgz http://cfengineers.net/files/src/cfengine-$(CFENGINE_RELEASE).tar.gz
	$(TAR) xzf $(TMP_DIR)/cfengine.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/cfengine-$(CFENGINE_RELEASE) $(BUILD_DIR)/cfengine-source

$(BUILD_DIR)/tokyocabinet-source:
	# Original URL: http://fallabs.com/tokyocabinet/tokyocabinet-${TOKYOCABINET_RELEASE}.tar.gz
	$(WGET) -O $(TMP_DIR)/tokyocabinet.tgz http://www.normation.com/tarball/tokyocabinet-${TOKYOCABINET_RELEASE}.tar.gz
	$(TAR) xzf $(TMP_DIR)/tokyocabinet.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/tokyocabinet-$(TOKYOCABINET_RELEASE) $(BUILD_DIR)/tokyocabinet-source

$(BUILD_DIR)/pcre-source:
	$(WGET) -O $(TMP_DIR)/pcre.tgz http://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-$(PCRE_RELEASE).tar.gz
	$(TAR) xzf $(TMP_DIR)/pcre.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/pcre-$(PCRE_RELEASE) $(BUILD_DIR)/pcre-source

$(BUILD_DIR)/openssl-source:
	$(WGET) -O $(TMP_DIR)/openssl.tgz http://www.openssl.org/source/openssl-$(OPENSSL_RELEASE).tar.gz
	$(TAR) xzf $(TMP_DIR)/openssl.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/openssl-$(OPENSSL_RELEASE) $(BUILD_DIR)/openssl-source

$(BUILD_DIR)/zlib-source:
	$(WGET) -O $(TMP_DIR)/zlib.tgz http://zlib.net/zlib-$(ZLIB_RELEASE).tar.gz
	$(TAR) xzf $(TMP_DIR)/zlib.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/zlib-$(ZLIB_RELEASE) $(BUILD_DIR)/zlib-source

$(BUILD_DIR)/bzip2-source:
	$(WGET) -O $(TMP_DIR)/bzip2.tgz http://www.bzip.org/1.0.6/bzip2-$(BZIP2_RELEASE).tar.gz
	$(TAR) xzf $(TMP_DIR)/bzip2.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/bzip2-$(BZIP2_RELEASE) $(BUILD_DIR)/bzip2-source

$(BUILD_DIR)/libxml2-source:
	$(WGET) -O $(TMP_DIR)/libxml2.tgz http://xmlsoft.org/sources/libxml2-$(LIBXML2_RELEASE).tar.gz
	$(TAR) xzf $(TMP_DIR)/libxml2.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/libxml2-$(LIBXML2_RELEASE) $(BUILD_DIR)/libxml2-source

$(BUILD_DIR)/libiconv-source:
	$(WGET) -O $(TMP_DIR)/libiconv.tgz http://ftp.gnu.org/pub/gnu/libiconv/libiconv-$(LIBICONV_RELEASE).tar.gz 
	$(TAR) xzf $(TMP_DIR)/libiconv.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/libiconv-$(LIBICONV_RELEASE) $(BUILD_DIR)/libiconv-source

$(BUILD_DIR)/openldap-source:
	$(WGET) -O $(TMP_DIR)/openldap.tgz http://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-$(OPENLDAP_RELEASE).tgz
	$(TAR) xzf $(TMP_DIR)/openldap.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/openldap-$(OPENLDAP_RELEASE) $(BUILD_DIR)/openldap-source

$(BUILD_DIR)/libuuid-source:
	$(WGET) -O $(TMP_DIR)/libuuid.tgz http://heanet.dl.sourceforge.net/project/libuuid/libuuid-$(LIBUUID_RELEASE).tar.gz
	$(TAR) xzf $(TMP_DIR)/libuuid.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/libuuid-$(LIBUUID_RELEASE) $(BUILD_DIR)/libuuid-source

$(BUILD_DIR)/expat-source:
	$(WGET) -O $(TMP_DIR)/expat.tgz http://freefr.dl.sourceforge.net/project/expat/expat/$(EXPAT_RELEASE)/expat-$(EXPAT_RELEASE).tar.gz
	$(TAR) xzf $(TMP_DIR)/expat.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/expat-$(EXPAT_RELEASE) $(BUILD_DIR)/expat-source

$(BUILD_DIR)/apr-source:
	$(WGET) -O $(TMP_DIR)/apr.tgz http://apache.vianett.no/apr/apr-$(APR_RELEASE).tar.gz
	$(TAR) xzf $(TMP_DIR)/apr.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/apr-$(APR_RELEASE) $(BUILD_DIR)/apr-source

$(BUILD_DIR)/nxlog-source:
	$(WGET) -O $(TMP_DIR)/nxlog.tgz http://nxlog.org/system/files/products/files/1/nxlog-ce-$(NXLOG_RELEASE).tar.gz
	$(TAR) xzf $(TMP_DIR)/nxlog.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/nxlog-ce-$(NXLOG_RELEASE) $(BUILD_DIR)/nxlog-ce-source

$(BUILD_DIR)/yaml-source:
	$(WGET) -O $(TMP_DIR)/yaml.tgz http://pyyaml.org/download/libyaml/yaml-$(YAML_RELEASE).tar.gz
	$(TAR) xzf $(TMP_DIR)/yaml.tgz -C $(TMP_DIR)
	mv $(TMP_DIR)/yaml-$(YAML_RELEASE) $(BUILD_DIR)/yaml-source

veryclean:
	rm -rf $(BUILD_DIR)/rudder-sources.tar.bz2

.PHONY: localclean localdepends veryclean
