#!/bin/sh

if [ -x /usr/bin/zonename ]; then
        for b in cf-execd cf-monitord cf-serverd cf-agent cf-hub; do
                /usr/bin/pkill -TERM -z `/usr/bin/zonename` $b
        done
else
        for b in cf-execd cf-monitord cf-serverd cf-agent cf-hub; do
                /usr/bin/pkill -TERM $b
        done
fi
/usr/bin/rm -f /etc/rc3.d/S97cf-elk /etc/rc0.d/K05cf-elk /etc/rc1.d/K05cf-elk \
        /etc/rc2.d/K05cf-elk /etc/rcS.d/K05cf-elk 

exit 0
